### ISSUE TITLE
Memory leak in 2.0.19

### ISSUE THREAD

**Issue by AudunWA** [ortexx/express-form-data#16] opened 2023-01-10 11:30 UTC
After upgrading `express-form-data` from 2.0.18 to 2.0.19, we started experiencing memory leaks on our express backend.

See this chart of memory usage. Left side (blue) is after we upgraded to 2.0.19, and right side (red) is when we downgraded. The spikes in the graph are when an instance runs out of memory and restarts. 
![image](https://user-images.githubusercontent.com/14100405/211539279-3b97cbcf-67f6-4b57-be7b-fb2e818bebe5.png)
This change was done in isolation – no other code was changed.

I am not familiar with the code base of `express-form-data`, but I suspect that this line might be the cause of the leak:
https://github.com/ortexx/express-form-data/commit/a86a1881440d7b57fedc0b4c1c34c57a12afcc60#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R90
`onExit(() => cleanSync(req.files));`.
If I understand correctly, an exit event listener gets added every time `parse` is called, and they never get cleaned (as it cleans on application exit).

**Comment by aolvictim** [comment] 2023-02-21 22:45
I have the exact same problem. Memory usage can grow quite fast from simply hitting our API's health check endpoint every 30 seconds.

The problem is exactly the line @AudunWA mentioned. Every request triggers that line to be called which causes the process to be never completed. Let's say the server gets 100 requests, `cleanSync` will run 100 times the moment you exit the program.

I will just stick with `2.0.18` for now.

**Comment by ortexx** [comment] 2023-02-22 06:05
Guys, thanks for your report. I don't have enough time to dive deep into the issue, but your conclusions seems right. So, test please the last fixes and give the feedback. If it doesn't work I will find the time to resolve it anyway.

**Comment by aolvictim** [comment] 2023-02-22 16:36
Even with the latest code, the problem is still there. That is due to the `req` being passed to `cleanSync(req.files)`. Whenever variables are still referenced, they do not get garbage collected. I don't think there is an easy way for a middleware to worry about cleaning up when the server fails. It should be the server's job.

But I propose just don't worry about cleaning up the `tmp` folder, it really is for the OS to handle. `tmp` gets cleared every reboot or can be set up to delete files that have not been accessed for a certain amount of time.

**Comment by ortexx** [comment] 2023-02-22 18:00
There are no such references here. The script just creates process.exit listener and removes it right after the request finished.

I can see the leak in .19 version how you said, but can't see it in the last versions .20+, using recursive requesting. Memory gets released in some time and everything looks fine.

You sure you are testing one of the last versions? 
.22 version is the most decent, btw.

**Closed as completed** 2023-03-05 04:44 UTC
